spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC # 로컬 개발 환경과 운영 서버 환영(UTC)간의 시간 불일치 예방

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

swagger:
  server:
    url: https://re-cap.duckdns.org

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
  refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}

apple:
  bundle-id: ${APPLE_BUNDLE_ID}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket-name: ${S3_BUCKET_NAME}

gemini:
  api-key: ${GEMINI_API_KEY}
  model-name: ${GEMINI_MODEL_NAME:gemini-2.5-flash}